name: mtc-webui

x-db-env: &db-env
  DATABASE_URL: postgres://${POSTGRES_USER:-mtc}:${POSTGRES_PASSWORD:-mtc}@database:5432/${POSTGRES_DB:-mtc}
  PGSSLROOTCERT: ""

services:
  database:
    image: postgres:18
    container_name: mtc-webui-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mtc}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mtc}
      POSTGRES_DB: ${POSTGRES_DB:-mtc}
      TZ: ${TZ:-Asia/Ho_Chi_Minh}
    ports:
      - "5433:5432"
    volumes:
      - mtc-webui-db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-mtc} -d $${POSTGRES_DB:-mtc}"]
      interval: 10s
      timeout: 3s
      start_period: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - mtc-webui

volumes:
  mtc-webui-db-data:
    name: mtc-webui-db-data

networks:
  mtc-webui:
    name: mtc-webui
    driver: bridge
